# Generated by Django 3.1 on 2022-04-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_totle',
            new_name='order_total',
        ),
    ]
