# Generated by Django 3.1 on 2022-04-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220416_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
